name: Build Flet APK

on:
  push:
    branches:
      - main  # Change this to your main branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install flet pyinstaller buildozer

      - name: Build Flet App Executable
        run: |
          pyinstaller --onefile my_app/bin/main.py  # Adjust this if your main script is named differently

      - name: Prepare for APK build
        run: |
          mkdir -p my_app/bin
          mv dist/main my_app/bin/  # Move the executable to the correct folder for Buildozer

      - name: Create Buildozer Spec
        run: |
          cd my_app
          buildozer init  # Creates a buildozer.spec file
          echo 'requirements = python3,flet' >> buildozer.spec  # Add Flet as a requirement

      - name: Build APK
        run: |
          cd my_app
          buildozer -v android debug  # Builds the APK

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyFletApp-debug.apk
          path: my_app/bin/*.apk  # Adjust this path based on your app's output directory

        with:
          name: MyFletApp-debug.apk
          path: my_app/bin/*.apk  # Adjust this path based on your app's output directory
