name: Build Flet APK

on:
  push:
    branches:
      - main  # Adjust if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install system dependencies including ldd
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tar gzip libc-bin

      - name: Verify tar and ldd installation
        run: |
          which tar
          tar --version
          which ldd
          ldd --version

      - name: Print Environment Variables
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "PATH: $PATH"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'  # Specify the Python version

      - name: Install Python dependencies
        run: |
          pip install flet pyinstaller buildozer cython

      - name: Install Android SDK
        run: |
          # Clean up any existing cmdline-tools directory
          rm -rf $HOME/android-sdk/cmdline-tools
          mkdir -p $HOME/android-sdk/cmdline-tools
          
          # Download and unzip the command line tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          rm commandlinetools-linux-9477386_latest.zip
          
          # Move the contents to the expected directory structure
          mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          # Set ANDROID_HOME environment variable
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=\$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:/usr/bin" >> $GITHUB_ENV

          # Accept licenses and install required components
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      - name: Manual JDK Installation
        run: |
          # Download Java 11
          wget https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.24%2B8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.24_8.tar.gz
          # Test Tar
          tar -cvf test.tar /tmp  # Just a simple test to create a tar file
          # Extract Java
          tar -xzf OpenJDK11U-jdk_x64_linux_hotspot_11.0.24_8.tar.gz
          # Move to the appropriate directory
          sudo mv jdk-11.0.24+8 /usr/lib/jvm/
          # Set JAVA_HOME and update PATH
          echo "JAVA_HOME=/usr/lib/jvm/jdk-11.0.24+8" >> $GITHUB_ENV
          echo "PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV

      - name: Verify Java installation
        run: |
          java -version

      - name: Build Flet App Executable
        env:
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.5/x64/lib  # Ensure ldd can find the libraries
        run: |
          pyinstaller --onefile main.py  # Ensure this matches your main script name

      - name: Prepare for APK build
        run: |
          mkdir -p my_app/bin
          mv dist/main my_app/bin/  # Move the executable to the correct folder for Buildozer

      - name: Create Buildozer Spec
        run: |
          cd my_app
          buildozer init  # Creates a buildozer.spec file
          echo 'requirements = python3,flet' >> buildozer.spec  # Add Flet as a requirement

      - name: Build APK
        run: |
          cd my_app
          buildozer -v android debug  # Builds the APK

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyFletApp-debug.apk
          path: my_app/bin/*.apk  # Adjust this path based on your app's output directory
