name: Build Flet APK

on:
  push:
    branches:
      - main  # Adjust if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install flet pyinstaller buildozer cython

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          rm commandlinetools-linux-9477386_latest.zip
          # Create the directory for the cmdline-tools if it doesn't exist
          mkdir -p cmdline-tools/latest
          # Move the extracted cmdline-tools to the latest folder
          mv cmdline-tools/* cmdline-tools/latest/
          # Clean up the empty cmdline-tools directory
          rmdir cmdline-tools
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-30"


      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Flet App Executable
        run: |
          pyinstaller --onefile main.py  # Ensure this matches your main script name

      - name: Prepare for APK build
        run: |
          mkdir -p my_app/bin
          mv dist/main my_app/bin/  # Move the executable to the correct folder for Buildozer

      - name: Create Buildozer Spec
        run: |
          cd my_app
          buildozer init  # Creates a buildozer.spec file
          echo 'requirements = python3,flet' >> buildozer.spec  # Add Flet as a requirement

      - name: Build APK
        run: |
          cd my_app
          buildozer -v android debug  # Builds the APK

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyFletApp-debug.apk
          path: my_app/bin/*.apk  # Adjust this path based on your app's output directory
